### ISSUE TITLE
Pass environment parameters to executors within jobs

### ISSUE THREAD

**Issue by gretzky** [verypossible-labs/rn-circleci-orb#3]
## Current Behavior

Our predefined jobs (`android_build`, etc.) declare which executor they should use, but they don't have an option to extend/overwrite any environment parameters.

e.g. `android_build` uses the `linux_android` executor, which has environment parameters for node (`NODE_OPTIONS`), java (`_JAVA_OPTIONS`), gradle (`GRADLE_OPTS`). The executor used standalone can handle passed parameters, but if you try to pass parameters to `android_build` job with the intent of piping them up to the `linux_android` executor, they won't get there.

## Desired Behavior

Allow our custom jobs to accept environment parameters for their given executors.

## Suggested Solution

There may be a few ways to do this, I'm not entirely sure which one would work or be best:

1. Determine if you can shim the environment parameters into the jobs as they exist now, without needing to change any code

e.g.
```yml
rn/android_build:
  environment:
    node_options: "--max-old-space-size=4196"
  ...other job params
```

2. Pass the executor params into the jobs params, and extend them into the executor.

e.g.
```yml
parameters:
   // executor params
   java_options:
       description: ""
       type: string
       default: ""
   // build job params
   project_path:

executor: linux_android
  node_options: <<parameters.java_options>>
```

3. Pass the executor itself as a param into the job params and allow the user to change it entirely.

```yml
parameters:
  executor:
      description: ""
      type: enum
      enum: ["linux_js", "linux_android, "macos"]
      default: "linux_android"

executor: <<parameters.executor>>
  java_options: ""
```

### Who does this impact? Who is it for?

Anyone that needs/wants to extend environment parameters passed into a predefined executor, in a predefined job.

### Describe alternatives you've considered

Leaving it as-is and having the user determine the best workaround for their situation. The downside here is that they would basically be copying the entire predefined job they need and just changing the executor.

## Additional Context

N/A
